version: '3'

services:
  pg:
    image: postgres
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - ./db-data/pg-data:/var/lib/postgresql/data/
#  redis:
#    image: 'redis:alpine'
#    ports:
#      - 6379:6379
#    volumes:
#      - ./db-data/redis-data:/var/lib/redis
#  mongo:
#    image: mongo
#    ports:
#      - 27017:27017
#    volumes:
#      - ./db-data/monge-data:/data/db
