version: '3.2'

services:
#  stocks_app:
#    build:
#      dockerfile: ./web_app/Dockerfile
#      context: ./web_app
  database_local:
    image: postgres:12
    environment:
      POSTGRES_DB: "STOCKS_DB"
      POSTGRES_USER: "USER"
      POSTGRES_PASSWORD: "PASSWORD"
    volumes:
      - ./db_data/pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
